# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#maodificação

#Funçlão responsavel mostra janelas de aviso
from PyQt5.QtWodgets import QMessageBox

from cadastro import Cadastro
from pessoa import Pessoa

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(433, 479)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_Nome_cadastrar = QtWidgets.QLabel(self.centralwidget)
        self.label_Nome_cadastrar.setObjectName("label_Nome_cadastrar")
        self.gridLayout.addWidget(self.label_Nome_cadastrar, 0, 0, 1, 1)
        self.label_Cadastro_CPF = QtWidgets.QLabel(self.centralwidget)
        self.label_Cadastro_CPF.setObjectName("label_Cadastro_CPF")
        self.gridLayout.addWidget(self.label_Cadastro_CPF, 1, 0, 1, 1)
        self.label_Cadastro_Endereco = QtWidgets.QLabel(self.centralwidget)
        self.label_Cadastro_Endereco.setObjectName("label_Cadastro_Endereco")
        self.gridLayout.addWidget(self.label_Cadastro_Endereco, 2, 0, 1, 1)
        self.label_Cadastro_Nascimento = QtWidgets.QLabel(self.centralwidget)
        self.label_Cadastro_Nascimento.setObjectName("label_Cadastro_Nascimento")
        self.gridLayout.addWidget(self.label_Cadastro_Nascimento, 3, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_Cadastro_Nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Cadastro_Nome.setObjectName("lineEdit_Cadastro_Nome")
        self.verticalLayout.addWidget(self.lineEdit_Cadastro_Nome)
        self.lineEdit_Cadastro_CPF = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Cadastro_CPF.setObjectName("lineEdit_Cadastro_CPF")
        self.verticalLayout.addWidget(self.lineEdit_Cadastro_CPF)
        self.lineEdit_Cadastro_Endereco = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Cadastro_Endereco.setObjectName("lineEdit_Cadastro_Endereco")
        self.verticalLayout.addWidget(self.lineEdit_Cadastro_Endereco)
        self.lineEdit_Cadastro_Nascimento = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Cadastro_Nascimento.setObjectName("lineEdit_Cadastro_Nascimento")
        self.verticalLayout.addWidget(self.lineEdit_Cadastro_Nascimento)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.pushButton_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cadastrar.setObjectName("pushButton_cadastrar")
        self.verticalLayout_2.addWidget(self.pushButton_cadastrar)
        self.listView_Cadastros_feitos = QtWidgets.QListView(self.centralwidget)
        self.listView_Cadastros_feitos.setObjectName("listView_Cadastros_feitos")
        self.verticalLayout_2.addWidget(self.listView_Cadastros_feitos)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_Busca = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.label_Busca.setFont(font)
        self.label_Busca.setObjectName("label_Busca")
        self.verticalLayout_4.addWidget(self.label_Busca)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.lineEdit_Busca_CPF = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Busca_CPF.setObjectName("lineEdit_Busca_CPF")
        self.horizontalLayout_2.addWidget(self.lineEdit_Busca_CPF)
        self.pushButton_Buscar_busca = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Buscar_busca.setObjectName("pushButton_Buscar_busca")
        self.horizontalLayout_2.addWidget(self.pushButton_Buscar_busca)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.listWidget_Busca = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_Busca.setObjectName("listWidget_Busca")
        self.verticalLayout_6.addWidget(self.listWidget_Busca)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        '''modificações'''
        self.cad = Cadastro()
        #Adicionar alterações ao bnotão cadastro
        self.pushButton_cadastrar.clicked.connect(self.bor)
        self.pushButton_Buscar_busca.connect()



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Cadastro"))
        self.label_Nome_cadastrar.setText(_translate("MainWindow", "Nome"))
        self.label_Cadastro_CPF.setText(_translate("MainWindow", "CPF"))
        self.label_Cadastro_Endereco.setText(_translate("MainWindow", "Endereço"))
        self.label_Cadastro_Nascimento.setText(_translate("MainWindow", "Nascimento"))
        self.pushButton_cadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.label_Busca.setText(_translate("MainWindow", "Busca"))
        self.label_7.setText(_translate("MainWindow", "CPF"))
        self.pushButton_Buscar_busca.setText(_translate("MainWindow", "Buscar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
