# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Busca.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Busca(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(300, 250))
        self.centralwidget.setStyleSheet("background-color: rgb(99, 99, 99);\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_busca_cabecalio = QtWidgets.QFrame(self.frame)
        self.frame_busca_cabecalio.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_busca_cabecalio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_busca_cabecalio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_busca_cabecalio.setObjectName("frame_busca_cabecalio")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_busca_cabecalio)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_Buca = QtWidgets.QLabel(self.frame_busca_cabecalio)
        self.label_Buca.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Buca.setFont(font)
        self.label_Buca.setStyleSheet("color: rgb(230, 230, 230);\n"
"margin-left: 108px;\n"
"margin-right: 100px;\n"
"")
        self.label_Buca.setObjectName("label_Buca")
        self.verticalLayout_5.addWidget(self.label_Buca)
        self.verticalLayout_3.addWidget(self.frame_busca_cabecalio)
        self.frame_busca = QtWidgets.QFrame(self.frame)
        self.frame_busca.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_busca.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_busca.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_busca.setObjectName("frame_busca")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_busca)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_busca_cpf = QtWidgets.QLabel(self.frame_busca)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_busca_cpf.setFont(font)
        self.label_busca_cpf.setStyleSheet("color: rgb(230, 230, 230);")
        self.label_busca_cpf.setObjectName("label_busca_cpf")
        self.verticalLayout_6.addWidget(self.label_busca_cpf)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_busca_cpf = QtWidgets.QLineEdit(self.frame_busca)
        self.lineEdit_busca_cpf.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding 15px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(230, 230, 230);\n"
"}")
        self.lineEdit_busca_cpf.setObjectName("lineEdit_busca_cpf")
        self.horizontalLayout_2.addWidget(self.lineEdit_busca_cpf)
        self.pushButton_busca_buscar = QtWidgets.QPushButton(self.frame_busca)
        self.pushButton_busca_buscar.setMinimumSize(QtCore.QSize(50, 20))
        self.pushButton_busca_buscar.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-position: center;\n"
"    background-color: rgb(255, 85, 127);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"")
        self.pushButton_busca_buscar.setObjectName("pushButton_busca_buscar")
        self.horizontalLayout_2.addWidget(self.pushButton_busca_buscar)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.frame_busca)
        self.frame_informacao = QtWidgets.QFrame(self.frame)
        self.frame_informacao.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_informacao.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_informacao.setObjectName("frame_informacao")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_informacao)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_busca_nome = QtWidgets.QLabel(self.frame_informacao)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_busca_nome.setFont(font)
        self.label_busca_nome.setStyleSheet("color: rgb(230, 230, 230);")
        self.label_busca_nome.setObjectName("label_busca_nome")
        self.verticalLayout_2.addWidget(self.label_busca_nome)
        self.label_busca_endereco = QtWidgets.QLabel(self.frame_informacao)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_busca_endereco.setFont(font)
        self.label_busca_endereco.setStyleSheet("color: rgb(230, 230, 230);")
        self.label_busca_endereco.setObjectName("label_busca_endereco")
        self.verticalLayout_2.addWidget(self.label_busca_endereco)
        self.label_busca_nascimento = QtWidgets.QLabel(self.frame_informacao)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_busca_nascimento.setFont(font)
        self.label_busca_nascimento.setStyleSheet("color: rgb(230, 230, 230);")
        self.label_busca_nascimento.setObjectName("label_busca_nascimento")
        self.verticalLayout_2.addWidget(self.label_busca_nascimento)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_busca_nome = QtWidgets.QLineEdit(self.frame_informacao)
        self.lineEdit_busca_nome.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding 15px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(230, 230, 230);\n"
"}")
        self.lineEdit_busca_nome.setPlaceholderText("")
        self.lineEdit_busca_nome.setObjectName("lineEdit_busca_nome")
        self.verticalLayout.addWidget(self.lineEdit_busca_nome)
        self.lineEdit_busca_endereco = QtWidgets.QLineEdit(self.frame_informacao)
        self.lineEdit_busca_endereco.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding 15px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(230, 230, 230);\n"
"}")
        self.lineEdit_busca_endereco.setPlaceholderText("")
        self.lineEdit_busca_endereco.setObjectName("lineEdit_busca_endereco")
        self.verticalLayout.addWidget(self.lineEdit_busca_endereco)
        self.lineEdit_busca_nascimento = QtWidgets.QLineEdit(self.frame_informacao)
        self.lineEdit_busca_nascimento.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding 15px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(230, 230, 230);\n"
"}")
        self.lineEdit_busca_nascimento.setPlaceholderText("")
        self.lineEdit_busca_nascimento.setObjectName("lineEdit_busca_nascimento")
        self.verticalLayout.addWidget(self.lineEdit_busca_nascimento)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.frame_informacao)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_voltar = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_voltar.setGeometry(QtCore.QRect(110, 10, 75, 23))
        self.pushButton_voltar.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-position: center;\n"
"    background-color: rgb(255, 85, 127);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"")
        self.pushButton_voltar.setObjectName("pushButton_voltar")
        self.verticalLayout_3.addWidget(self.frame_2)
        self.verticalLayout_4.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Buca.setText(_translate("MainWindow", "Busca"))
        self.label_busca_cpf.setText(_translate("MainWindow", "Informe o CPF :"))
        self.pushButton_busca_buscar.setText(_translate("MainWindow", "Buscar"))
        self.label_busca_nome.setText(_translate("MainWindow", "Nome"))
        self.label_busca_endereco.setText(_translate("MainWindow", "Endereco"))
        self.label_busca_nascimento.setText(_translate("MainWindow", "Nascimento"))
        self.pushButton_voltar.setText(_translate("MainWindow", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Busca()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
