# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_0_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

#Funçlão responsavel mostra janelas de aviso
from PyQt5.QtWidgets import QMessageBox

from cadastro import Cadastro
from pessoa import Pessoa

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(295, 360)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 30, 247, 310))
        self.widget.setObjectName("widget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_Cadatro = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Cadatro.setFont(font)
        self.label_Cadatro.setObjectName("label_Cadatro")
        self.verticalLayout_9.addWidget(self.label_Cadatro)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_Cadastro_nome = QtWidgets.QLabel(self.widget)
        self.label_Cadastro_nome.setObjectName("label_Cadastro_nome")
        self.horizontalLayout.addWidget(self.label_Cadastro_nome)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_Cadastro_endereco = QtWidgets.QLabel(self.widget)
        self.label_Cadastro_endereco.setObjectName("label_Cadastro_endereco")
        self.horizontalLayout_2.addWidget(self.label_Cadastro_endereco)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_Cadastro_CPF = QtWidgets.QLabel(self.widget)
        self.label_Cadastro_CPF.setObjectName("label_Cadastro_CPF")
        self.horizontalLayout_3.addWidget(self.label_Cadastro_CPF)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_Cadastro_Nascimento = QtWidgets.QLabel(self.widget)
        self.label_Cadastro_Nascimento.setObjectName("label_Cadastro_Nascimento")
        self.horizontalLayout_4.addWidget(self.label_Cadastro_Nascimento)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEdit_Cadastro_nome = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Cadastro_nome.setObjectName("lineEdit_Cadastro_nome")
        self.verticalLayout_7.addWidget(self.lineEdit_Cadastro_nome)
        self.lineEdit_Cadastro_endereco = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Cadastro_endereco.setObjectName("lineEdit_Cadastro_endereco")
        self.verticalLayout_7.addWidget(self.lineEdit_Cadastro_endereco)
        self.lineEdit_Cadastro_CPF = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Cadastro_CPF.setObjectName("lineEdit_Cadastro_CPF")
        self.verticalLayout_7.addWidget(self.lineEdit_Cadastro_CPF)
        self.lineEdit_Cadastro_Nascimento = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Cadastro_Nascimento.setObjectName("lineEdit_Cadastro_Nascimento")
        self.verticalLayout_7.addWidget(self.lineEdit_Cadastro_Nascimento)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.pushButton_Cadastro_cadsatrar = QtWidgets.QPushButton(self.widget)
        self.pushButton_Cadastro_cadsatrar.setObjectName("pushButton_Cadastro_cadsatrar")
        self.verticalLayout_8.addWidget(self.pushButton_Cadastro_cadsatrar)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_Busca = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Busca.setFont(font)
        self.label_Busca.setObjectName("label_Busca")
        self.verticalLayout_3.addWidget(self.label_Busca)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_Busca_cpf = QtWidgets.QLabel(self.widget)
        self.label_Busca_cpf.setObjectName("label_Busca_cpf")
        self.horizontalLayout_5.addWidget(self.label_Busca_cpf)
        self.lineEdit_Busca_cpf = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Busca_cpf.setObjectName("lineEdit_Busca_cpf")
        self.horizontalLayout_5.addWidget(self.lineEdit_Busca_cpf)
        self.pushButton_Busca_buscar = QtWidgets.QPushButton(self.widget)
        self.pushButton_Busca_buscar.setObjectName("pushButton_Busca_buscar")
        self.horizontalLayout_5.addWidget(self.pushButton_Busca_buscar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_Busca_nome = QtWidgets.QLabel(self.widget)
        self.label_Busca_nome.setObjectName("label_Busca_nome")
        self.verticalLayout_4.addWidget(self.label_Busca_nome)
        self.label_Busca_endereco = QtWidgets.QLabel(self.widget)
        self.label_Busca_endereco.setObjectName("label_Busca_endereco")
        self.verticalLayout_4.addWidget(self.label_Busca_endereco)
        self.label_Busca_nascimento = QtWidgets.QLabel(self.widget)
        self.label_Busca_nascimento.setObjectName("label_Busca_nascimento")
        self.verticalLayout_4.addWidget(self.label_Busca_nascimento)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_Busca_nome = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Busca_nome.setObjectName("lineEdit_Busca_nome")
        self.verticalLayout_5.addWidget(self.lineEdit_Busca_nome)
        self.lineEdit_Busca_endereco = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Busca_endereco.setObjectName("lineEdit_Busca_endereco")
        self.verticalLayout_5.addWidget(self.lineEdit_Busca_endereco)
        self.lineEdit_Busca_nascimento = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Busca_nascimento.setObjectName("lineEdit_Busca_nascimento")
        self.verticalLayout_5.addWidget(self.lineEdit_Busca_nascimento)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_10.addLayout(self.verticalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        '''modificação'''
        self.cadastro = Cadastro()
        #Adicionar alterações ao bnotão cadastro
        self.pushButton_Cadastro_cadsatrar.clicked.connect(self.botaoCadastra)
        self.pushButton_Busca_buscar.clicked.connect(self.botaoBusca)


    def botaoCadastra(self):
        nome = self.lineEdit_Cadastro_nome.text()
        endereco = self.lineEdit_Cadastro_endereco.text()
        cpf = self.lineEdit_Cadastro_CPF.text()
        nascimento = self.lineEdit_Cadastro_Nascimento.text()
        if not(nome == '' or endereco == '' or cpf == '' or nascimento == '') :
            pessoa = Pessoa(nome,endereco,cpf,nascimento)
            if (self.cadastro.cadastra(pessoa)):
                QMessageBox.information(None,'POOII','Cadastro realizado com sucesso!')
                #Apagar os campos apos cadastrar
                self.lineEdit_Cadastro_nome.setText('')
                self.lineEdit_Cadastro_endereco.setText('')
                self.lineEdit_Cadastro_CPF.setText('')
                self.lineEdit_Cadastro_Nascimento.setText('')
            else:
                QMessageBox.information(None,'POOII','O CPF informado já está cadastrado na base de dados')
        else:
            QMessageBox.information(None,'POOII','Todos os valores deven ser preenchidos!')

    def botaoBusca(self):
        cpf = self.lineEdit_Busca_cpf.text()
        pessoa = self.cadastro.busca(cpf)
        if (pessoa!=None):
            self.lineEdit_Busca_nome.setText(pessoa.nome)
            self.lineEdit_Busca_endereco.setText(pessoa.endereco)
            self.lineEdit_Busca_nascimento.setText(pessoa.nascimento)
            #QMessageBox.information(None,'POOII','Nome: {}\nEndereco: {}\nNascimento: {}'.format(pessoa.nome,pessoa.endereco,pessoa.nascimento))
        else:
            QMessageBox.information(None,'POOII','CPF informado não cadastrado')


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Cadatro.setText(_translate("MainWindow", "Cadastro"))
        self.label_Cadastro_nome.setText(_translate("MainWindow", "Nome"))
        self.label_Cadastro_endereco.setText(_translate("MainWindow", "Endereco"))
        self.label_Cadastro_CPF.setText(_translate("MainWindow", "CPF"))
        self.label_Cadastro_Nascimento.setText(_translate("MainWindow", "Nascimento"))
        self.pushButton_Cadastro_cadsatrar.setText(_translate("MainWindow", "Cadastrar"))
        self.label_Busca.setText(_translate("MainWindow", "Busca"))
        self.label_Busca_cpf.setText(_translate("MainWindow", "CPF"))
        self.pushButton_Busca_buscar.setText(_translate("MainWindow", "Buscar"))
        self.label_Busca_nome.setText(_translate("MainWindow", "Nome"))
        self.label_Busca_endereco.setText(_translate("MainWindow", "Endereco"))
        self.label_Busca_nascimento.setText(_translate("MainWindow", "Nascimento"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
